### ISSUE TITLE
checker.forEmber is not a function

### ISSUE THREAD

**Issue by olivierlesnicki** [rwjblue/ember-getowner-polyfill#17]
```
checker.forEmber is not a function
TypeError: checker.forEmber is not a function
    at CoreObject.module.exports.included (/node_modules/ember-getowner-polyfill/index.js:13:32)
```

**Comment by rwjblue** [comment]
This function was added in https://github.com/ember-cli/ember-cli-version-checker/pull/21 and released in ember-cli-version-checker@1.2.0 (which is what we depend on in our [package.json](https://github.com/rwjblue/ember-getowner-polyfill/blob/master/package.json#L49)).

My guess is that an addon is including ember-getowner-polyfill but also including an older version of ember-cli-version-checker. 

You can track that down via these two commands:

    npm ls ember-getowner-polyfill
    npm ls ember-cli-version-checker

**Comment by olivierlesnicki** [comment]
Ok thanks!

The error has currently disapeared (following a re-install of the node modules) (thanks to the non-deterministic nature of npm). If and when it re-appears will make sure to run the commands provided above.

**Comment by rwjblue** [comment]
Great, thanks for reporting and letting me know that it seems resolved.

**Comment by dirkdirk** [comment]
Re-install of node modules fixed it for me also: delete `./node_modules` then `$ npm install`
