### ISSUE TITLE
Version 1.2.2 seems to break Ember 2.0.2 app

### ISSUE THREAD

**Issue by jbryson3** [rwjblue/ember-getowner-polyfill#19]
Did an npm install today and `ember serve` is throwing errors in console:  
> Could not find module `ember-cli-version-checker` imported from `(require)`
(Line 4 of index.js in ember-factory-for-polyfill)

Looking into what's changed recently, I saw that ember-getowner-polyfill had bumped its version, and along with it, included a dependency on ember-factory-for-polyfill

Working shrinkwrap snippet
```
├─┬ ember-power-select@0.10.11
│ ├─┬ ember-basic-dropdown@0.11.7
│ │ ├── ember-get-config@0.0.2
│ │ ├── ember-getowner-polyfill@1.1.1
```

Broken shrinkwrap snippet
```
├─┬ ember-power-select@0.10.11
│ ├─┬ ember-basic-dropdown@0.11.7
│ │ ├── ember-get-config@0.0.2
│ │ ├─┬ ember-getowner-polyfill@1.2.2
│ │ │ └── ember-factory-for-polyfill@1.1.1
```

And though the documentation for ember-getowner-polyfill says it supports ember 1.10+, the docs for ember-factory-for-polyfill says it supports ember 2.3+ (https://github.com/rwjblue/ember-factory-for-polyfill/issues/4). 

Does this effectively mean that ember-getowner-polyfill only supports ember 2.3+?

**Comment by rwjblue** [comment]
> Does this effectively mean that ember-getowner-polyfill only supports ember 2.3+?

No, it means that using ember-factory-for-polyfill alone you get support for Ember 2.3 and higher, but when using ember-getowner-polyfill (which includes ember-factory-for-polyfill as a dep) you get 1.10+ support.

Also to note, [the documentation for ember-factory-for-polyfill](https://github.com/rwjblue/ember-factory-for-polyfill#compatibility) says this (right below the list of supported versions):

> For compatibility with older Ember versions prior to 2.3, please use ember-getowner-polyfill instead.

**Comment by rwjblue** [comment]
> Did an npm install today and ember serve is throwing errors in console

I'm not really sure where that error message is coming from actually.  [ember-factory-for-polyfill index.js#L4](https://github.com/rwjblue/ember-factory-for-polyfill/blob/master/index.js#L4) does `require('ember-cli-version-checker')` and it also [includes a dependency on that npm package](https://github.com/rwjblue/ember-factory-for-polyfill/blob/master/package.json#L22).  

Can you describe what you mean by "console" (e.g. terminal window running `ember s` vs browser console at runtime)? That error looks generally like an error the the `loader.js` package triggers at runtime in the browser ([see here](https://github.com/ember-cli/loader.js/blob/master/lib/loader/loader.js#L251)), but [this file](https://github.com/rwjblue/ember-factory-for-polyfill/blob/master/index.js) should never actually end up in the browser runtime (it should only ever be evaluated in node-land).

**Comment by jbryson3** [comment]
Apologies for not being more specific about 'console.' I meant my chrome browser console.

```
Uncaught Error: Could not find module `ember-cli-version-checker` imported from `(require)`
    at missingModule (loader.js:135)
    at findModule (loader.js:150)
    at requireModule (loader.js:139)
    at index.js:4
```

And it's definitely in the browser runtime, I'm not sure why.

**Comment by jbryson3** [comment]
I changed the path from ```node_modules/ember-factory-for-polyfill/vendor/ember-factory-for-polyfill/index.js``` to ```node_modules/ember-factory-for-polyfill/vendor/index.js``` and now it working. The app boots up, and is no longer shipping the ember-factory-for-polyfill to the browser.

I don't know why that would change anything.

**Comment by rwjblue** [comment]
Yeah, this is pretty confusing to be honest.  That file should not ever end up in the browser.  Something is going wonky in your build. 

I'd suggest creating a fresh app, and slowly bringing in the dependencies that your app has and see when this is introduced...

**Comment by jbryson3** [comment]
I still haven't figured out the root cause, but this is not the only project that can break the build. I have managed to tweak the versions of my dependencies to get things working again (Downgrading ember-cli-ic-ajax to 0.2.4 alleviate all my issues). Apologies for the false alarm, and thanks for the help.
