### ISSUE TITLE
Cut off date?

### ISSUE THREAD

**Issue by QuantumInformation** [rwjblue/ember-getowner-polyfill#24]
Any ideas when code throwing ` ember-getowner-polyfill is now a true polyfill` will break?

**Comment by rwjblue** [comment]
Not sure I understand. If you upgrade to ember-get owner-polyfill@2 you no longer get the deprecation (and the module is no longer present meaning that an error would be thrown).

**Comment by QuantumInformation** [comment]
I see, thx.
