### ISSUE TITLE
FakeOwner.registry.resolve is deprecated

### ISSUE THREAD

**Issue by kamal** [rwjblue/ember-getowner-polyfill#4]
Calling `FakeOwner.resolveRegistration` hits a deprecation warning

Using `ApplicationInstance.registry.resolve` is deprecated. Please use `ApplicationInstance.resolveRegistration` instead.

**Comment by rwjblue** [comment]
@kamal - Thanks for reporting, can you provide a demo ember-twiddle (they have addon support now)?

**Comment by rwjblue** [comment]
Ping @kamal?

**Comment by rwjblue** [comment]
Closing for now, please share a reproduction and I'm happy to jump on this....
