### ISSUE TITLE
Become a "real" polyfill.

### ISSUE THREAD

**Issue by rwjblue** [rwjblue/ember-getowner-polyfill#5]
Basic steps:

- [x] Monkey patch `Ember.getOwner` when Ember version is too old
- [x] Deprecate usage of `import getOwner from 'ember-getowner-polyfill';`, in favor of just using `Ember.getOwner`
- [x] Bump major versions, remove deprecated `import` support.
- [ ] Work on common/top addons to update to latest version (ongoing)

**Comment by workmanw** [comment]
@rwjblue 

> Bump major versions, remove deprecated import support.

Does this mean you would prefer for addons to wait on PRs until after this addon is 2.x? I just submitted a PR to `ember-i18n` to remove deprecations from my builds. But now I'm wondering if I should pause that until this addon is 2.x? Thoughts? Timeline for that?

**Comment by rwjblue** [comment]
>Does this mean you would prefer for addons to wait on PRs until after this addon is 2.x? 

@workmanw - No, I think we need to let things settle a bit before I release 2.0.0.  Sadly, this will be _some_ churn for addons but the bump from 1.1.0 to 2.0.0 will not introduce deprecations, so it should be a simple package.json bump when the time comes.

**Comment by rwjblue** [comment]
Looks like still a few addons needing to be updated https://emberobserver.com/code-search?codeQuery=import.*ember-getowner-polyfill&regex=true

**Comment by rwjblue** [comment]
Done and published.
